# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_auto_20161110_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d1mini',
            name='LastHeard',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
