# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_auto_20161115_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d1minicommand',
            old_name='Acknowledged',
            new_name='acknowledged',
        ),
        migrations.RenameField(
            model_name='d1minicommand',
            old_name='DateCommand',
            new_name='date_command',
        ),
        migrations.RenameField(
            model_name='d1minicommand',
            old_name='PinID',
            new_name='pin_id',
        ),
        migrations.RenameField(
            model_name='d1minievent',
            old_name='Acknowledged',
            new_name='acknowledged',
        ),
        migrations.RenameField(
            model_name='d1minievent',
            old_name='DateCommand',
            new_name='date_command',
        ),
        migrations.RenameField(
            model_name='d1minievent',
            old_name='PinID',
            new_name='pin_id',
        ),
        migrations.RemoveField(
            model_name='d1minicommand',
            name='PinLevel',
        ),
        migrations.RemoveField(
            model_name='d1minicommand',
            name='PinMode',
        ),
        migrations.RemoveField(
            model_name='d1minievent',
            name='PinMode',
        ),
        migrations.AddField(
            model_name='d1minicommand',
            name='pin_level',
            field=models.SmallIntegerField(choices=[(1, 'High'), (0, 'Low')], default=0),
        ),
        migrations.AddField(
            model_name='d1minicommand',
            name='pin_mode',
            field=models.SmallIntegerField(choices=[(0, 'Input'), (1, 'Output')], default=0),
        ),
        migrations.AddField(
            model_name='d1minievent',
            name='pin_level',
            field=models.SmallIntegerField(choices=[(1, 'High'), (0, 'Low')], default=0),
        ),
        migrations.AddField(
            model_name='d1minievent',
            name='pin_mode',
            field=models.SmallIntegerField(choices=[(0, 'Input'), (1, 'Output')], default=0),
        ),
        migrations.AlterField(
            model_name='d1mini',
            name='BuiltInLedLevel',
            field=models.CharField(choices=[(1, 'High'), (0, 'Low')], default='L', max_length=1),
        ),
    ]
