# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_auto_20161117_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='D1MiniReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_type', models.IntegerField(choices=[(0, 'Humidity'), (1, 'Temperature'), (2, 'Heat Index')])),
                ('reading_value', models.IntegerField(default=0)),
                ('reading_unit', models.IntegerField(choices=[(0, 'Percent'), (0, 'Celcius*'), (0, 'Fahrenheit'), (0, '*Celcius'), (0, '*Fahrenheit')])),
                ('date_reading', models.DateTimeField(auto_now=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.D1Mini')),
            ],
        ),
        migrations.AlterField(
            model_name='d1minicommand',
            name='pin_id',
            field=models.IntegerField(choices=[(2, 'LED_BUILTIN'), (16, 'D0'), (5, 'D1'), (4, 'D2'), (0, 'D3'), (2, 'D4'), (14, 'D5'), (12, 'D6'), (13, 'D7'), (15, 'D8'), (3, 'RX'), (1, 'TX')]),
        ),
        migrations.AlterField(
            model_name='d1minievent',
            name='pin_id',
            field=models.IntegerField(choices=[(2, 'LED_BUILTIN'), (16, 'D0'), (5, 'D1'), (4, 'D2'), (0, 'D3'), (2, 'D4'), (14, 'D5'), (12, 'D6'), (13, 'D7'), (15, 'D8'), (3, 'RX'), (1, 'TX')]),
        ),
    ]
