# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0009_auto_20161123_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d1minireading',
            name='reading_unit',
            field=models.IntegerField(choices=[(0, 'Percent'), (1, 'Celcius'), (2, 'Fahrenheit'), (3, 'Felt Air C'), (4, 'Felt Air F')]),
        ),
    ]
