# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_auto_20161123_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d1mini',
            old_name='MACID',
            new_name='mac_id',
        ),
        migrations.RemoveField(
            model_name='d1mini',
            name='BuiltInLedLevel',
        ),
    ]
