# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_auto_20161124_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='d1mini',
            name='has_dht',
            field=models.SmallIntegerField(default=0),
        ),
    ]
