# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0012_d1mini_has_dht'),
    ]

    operations = [
        migrations.AddField(
            model_name='d1mini',
            name='alias',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
