# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0013_d1mini_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controllable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_controls', models.CharField(max_length=32)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.D1Mini')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_id', models.SmallIntegerField(default=-1)),
                ('alias', models.CharField(max_length=50)),
                ('is_high', models.BooleanField(default=False)),
                ('is_inverse', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.D1Mini')),
            ],
        ),
    ]
